- name: install python3 packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: installed
  loop: 
  - python3 
  - gcc 
  - python3-devel

- name: download the dependencies
  ansible.builtin.pip:
    requirements: requirements.txt
    executable: pip3.9   # which version of application was designed
  args:
    chdir: /app